### ISSUE TITLE
TypeError: provider.use is not a function

### ISSUE THREAD

**Issue by psmiraglia** [panva/node-oidc-provider#237]
When in my Express app I try to define a custom middleware like that

```js
provider.use(async (ctx, next) => {
  console.log('My middleware >>>>>', ctx.path);
  await next();
  console.log('My middleware <<<<<', ctx._matchedRouteName);
});
```

I receive the the error

```
TypeError: provider.use is not a function
    at provider.initialize.then (/path/to/app.js:94:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

Apparently it seems to be solved if I use

```js
provider.app.use(async (ctx, next) => {
  //     ^^^
  console.log('My middleware >>>>>', ctx.path);
  await next();
  console.log('My middleware <<<<<', ctx._matchedRouteName);
});
```

Should the [documentation](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#pre--and-post-middlewares) be fixed?

Is it my fault?

**Comment by panva** [comment]
Which provider version are you using? This was only just recently added in 2.15.0

**Comment by psmiraglia** [comment]
I'm using the `2.14.0` version. I'll try by updating to `2.15.0`. In the meantime, I (apparently) solved with

```js
provider.app.middleware.unshift(async (ctx, next) => { ... });
```

**Comment by psmiraglia** [comment]
Confirmed. It works with `2.15.0`. Thanks!

**Comment by panva** [comment]
that's what the docs said for 2.14.0 yeah... 2.15.0 just makes it built in and preserves the order of .use()
